name: run soccer data

# on: [push]
# on:
  # schedule:
  #   - cron: "00 23 * * *"    #runs at 23:00 UTC everyday

on:
  # Cron to run once a day at 6am PT
  schedule:
    - cron: '0 15 * * *' # This is UTC time, so 6am PT is 1pm UTC
  # Allows the workflow to be triggered manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 # Install the python version needed

      - name: Install Python dependencies
        # run: python -m pip install --upgrade pip requests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --default-timeout=100
        
      - name: Execute Python script # Run the run.py to get the latest data
        run: python scripts/soccer_data.py

      - name: List files before push
        run: |
          ls -la
          git status

      - name: Commit and push changes
        run: |
          git config --global user.name "aaron"
          git config --global user.email "aaroncolesmith@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.BET_MODEL_GITHUB_TOKEN }}
